name: Publish to nuget
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: BserClient
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/conscrap/
  GITHUB_USER: FriendlyUser
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_API_KEY: ${{ secrets.NUGET_KEY }}

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - release/*
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'conscrap.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # - name: Get Build Version
    #   run: |
    #     Import-Module .\build\GetBuildVersion.psm1
    #     Write-Host $Env:GITHUB_REF
    #     $version = GetBuildVersion -VersionString $Env:GITHUB_REF
    #     echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    #   shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Publish Nuget
      if: startsWith(github.ref, 'refs/heads/release')
      run: |
        nuget setapikey "${{ secrets.NUGET_API_KEY }}" -Source 'https://api.nuget.org/v3/index.json'
        nuget push **\*.nupkg 
        dotnet nuget push **\*.nupkg --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github"